<script setup lang="ts">
import {ref} from 'vue'
import {api,backup,desktop,request,selectProfileSourceDirectory} from '../api'
import {useWorkspace} from '../workspace'
import Icon from './Icon.vue'
const w=useWorkspace(),source=ref(''),inspected=ref<Record<string,any>|null>(null),busy=ref(false),error=ref('')
async function run(fn:()=>Promise<unknown>){busy.value=true;error.value='';try{await fn();await w.boot()}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function inspect(){busy.value=true;error.value='';try{inspected.value=await api.inspect(source.value)}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function browse(){busy.value=true;error.value='';try{const chosen=await selectProfileSourceDirectory();if(chosen){source.value=chosen;inspected.value=null;await inspect()}}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function exportBackup(){busy.value=true;error.value='';try{if(await backup())w.notify('备份已导出')}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
</script>
<template><section class="page-view settings-view"><div class="page-header"><div><h1>数据与备份</h1><p>查看存储位置，初始化或导入现有数据。</p></div><button class="button" :disabled="busy" @click="w.boot()"><Icon name="refresh"/>刷新状态</button></div><p v-if="error||w.setup.value?.error" class="inline-error" role="alert">{{error||w.setup.value?.error}}</p><section class="settings-section"><h2>当前数据 <span class="badge">{{w.setup.value?.state==='ready'?'已就绪':'待初始化'}}</span></h2><dl class="path-list"><div><dt>数据根目录</dt><dd>{{w.setup.value?.data_root||'尚未读取'}}</dd></div><div><dt>订阅</dt><dd>{{w.setup.value?.profile_dir||'—'}}</dd></div><div><dt>历史</dt><dd>{{w.setup.value?.history_dir||'—'}}</dd></div><div><dt>设置</dt><dd>{{w.setup.value?.settings_file||'—'}}</dd></div></dl><div class="button-group"><button class="button" :disabled="busy" @click="request('/api/data/open-folder','POST',undefined,'OpenDataFolder').catch(w.fail)">打开数据目录</button><button class="button primary" :disabled="busy" @click="exportBackup"><Icon name="download"/>导出备份</button></div></section><section v-if="w.setup.value?.state!=='ready'" class="settings-section"><h2>选择开始方式</h2><p>当前尚未选择订阅存储。可以从已有数据导入，或创建空白存储后添加机场。</p><button class="button primary" :disabled="busy" @click="run(api.initialize)">创建空白存储</button></section><section class="settings-section"><h2>导入现有订阅</h2><p class="muted small">先检查来源，再导入；文件选择取消时保持当前数据。备份导出包含已有数据，恢复请按原有导入方式检查来源。</p><div class="inline-field"><input v-model="source" aria-label="现有订阅数据目录" placeholder="现有数据目录的绝对路径"><button v-if="desktop()" class="button" :disabled="busy" @click="browse"><Icon name="data"/>浏览目录</button><button class="button" :disabled="busy||!source.trim()" @click="inspect">检查来源</button></div><div v-if="inspected" class="source-inspection"><strong>{{inspected.label||inspected.path}}</strong><p>{{inspected.profile_count||0}} 个机场 · {{inspected.cache_count||0}} 份缓存</p><p v-if="inspected.error" class="bad">{{inspected.error}}</p><button class="button primary" :disabled="busy||!inspected.available" @click="run(()=>api.importSource(source))">导入这个来源</button></div><div v-for="s in w.setup.value?.sources" :key="s.path" class="compact-row"><span>{{s.label}}<small class="break-text">{{s.path}}</small></span><button class="button" :disabled="!s.available||busy" @click="source=s.path;inspect()">检查</button></div></section><section v-if="w.setup.value?.migration.state!=='ready'&&w.setup.value?.migration.state!=='isolated'" class="settings-section"><h2>旧版数据迁移</h2><p>{{w.setup.value?.migration.error||`迁移状态：${w.setup.value?.migration.state}`}}</p><button class="button" :disabled="busy||w.setup.value?.migration.state==='conflict'" @click="run(api.migrate)">迁移旧版历史与设置</button></section></section></template>
