<script setup lang="ts">
import {nodeDisplayName} from '../nodePresentation'
import UiSelect from './UiSelect.vue'
import {computed,ref} from 'vue'
import {api} from '../api'
import {useWorkspace} from '../workspace'
import {key,monitorGroups,type MonitorJob} from '../domain'
import Modal from './Modal.vue'
const w=useWorkspace(),name=ref('常用节点监测'),interval=ref(300),timeout=ref(5),probe=ref('latency_six_v1'),tier=ref('regular'),startNow=ref(true),resume=ref(false),working=ref(false),error=ref(''),selectionChanged=ref(false),created=ref<Record<string,MonitorJob>>({}),started=ref<string[]>([]),configured=ref<string[]>([])
const groups=computed(()=>monitorGroups(w.monitorNodes.value||[],name.value,interval.value,timeout.value,probe.value,tier.value))
function requireCurrentSelection(){const available=new Map(w.proxyNodes.value.map(n=>[key(n),n.node_key])),selected=w.monitorNodes.value||[];if(!selected.length||selected.some(n=>available.get(key(n))!==n.node_key)){selectionChanged.value=true;throw new Error('所选节点范围或配置已变化，请返回重新选择。')}}
async function create(){error.value='';selectionChanged.value=false;if(!name.value.trim()){error.value='请填写任务名称';return}working.value=true;try{requireCurrentSelection();for(const g of groups.value){requireCurrentSelection();let job=created.value[g.profile_id];if(!job){job=await api.createJob(g);created.value[g.profile_id]=job}requireCurrentSelection();if(!configured.value.includes(job.id)){await api.jobAction(job.id,'resume-on-launch',{enabled:resume.value});configured.value.push(job.id)}requireCurrentSelection();if(startNow.value&&!started.value.includes(job.id)){await api.jobAction(job.id,'start');started.value.push(job.id)}}await w.refreshJobs();w.notify(`已创建 ${Object.keys(created.value).length} 个监测任务`);w.monitorNodes.value=null;w.page.value='monitor'}catch(e){error.value=e instanceof Error?e.message:String(e);await w.refreshJobs().catch(()=>{})}finally{working.value=false}}
</script>
<template><Modal title="加入持续监测" wide @close="()=>{if(!working)w.monitorNodes.value=null}"><p class="modal-intro">已选 {{w.monitorNodes.value?.length}} 个节点，按订阅创建 {{groups.length}} 个任务。</p><fieldset :disabled="working||Object.keys(created).length>0" class="plain-fieldset"><div class="form-grid"><label>任务名称<input v-model="name" maxlength="100" placeholder="例如：常用节点监测"></label><label>检测间隔<UiSelect v-model.number="interval"><option :value="30">每 30 秒</option><option :value="60">每 1 分钟</option><option :value="300">每 5 分钟</option><option :value="900">每 15 分钟</option><option :value="3600">每 1 小时</option></UiSelect></label><label>检测项目<UiSelect v-model="probe"><option value="latency_six_v1">六站延迟 · Cloudflare / Google / GitHub / Apple / Microsoft / Firefox</option><option value="light">延迟与连接 · Cloudflare</option><option value="service">Cloudflare / Google / GitHub</option><option value="heavy">深度诊断 · 含流量采样</option></UiSelect></label><label>采样类型<UiSelect v-model="tier"><option value="regular">常规监测</option><option value="focus">重点监测</option><option value="sparse">稀疏监测</option></UiSelect></label><label>单项超时<UiSelect v-model.number="timeout"><option v-for="n in [3,5,10,20,30]" :key="n" :value="n">{{n}} 秒</option></UiSelect></label></div><label class="check-field"><input v-model="startNow" type="checkbox">创建后立即启动</label><label class="check-field"><input v-model="resume" type="checkbox">应用下次启动时继续运行</label></fieldset><div class="monitor-group" v-for="g in groups" :key="g.profile_id"><div><strong>{{g.name}}</strong><span class="badge" :class="created[g.profile_id]?'good':''">{{created[g.profile_id]?started.includes(created[g.profile_id].id)?'已启动':'已创建':'待创建'}} · {{g.node_keys.length}} 个节点</span></div><p>{{w.monitorNodes.value?.filter(n=>n.profile_id===g.profile_id).map(n=>nodeDisplayName(n)).join('、')}}</p></div><p v-if="error" class="inline-error" role="alert">{{error}}<span v-if="Object.keys(created).length">{{selectionChanged?'已成功创建的任务保留，可在持续监测页查看。':'。已成功创建的任务保留，再次提交只继续未完成部分。'}}</span></p><template #footer><button class="button" :disabled="working" @click="w.monitorNodes.value=null">返回</button><button class="button primary" :disabled="working||!groups.length" @click="create">{{working?'正在创建…':Object.keys(created).length?'继续未完成任务':`创建 ${groups.length} 个任务`}}</button></template></Modal></template>
