<script setup lang="ts">
import UiSelect from './UiSelect.vue'
import {computed,ref} from 'vue'
import type {ServiceRule} from '../domain'
import Icon from './Icon.vue'
const props=defineProps<{modelValue:string[];catalog:ServiceRule[]}>(),emit=defineEmits<{ 'update:modelValue':[value:string[]] }>(),search=ref(''),category=ref('')
function group(s:ServiceRule){return ['ipok_ipv4','ipok_ipv6','ippure_ip_quality','ping0_ip_quality','exit_ipv4','exit_ipv6'].includes(s.service_id)?'IP 画像与信誉':s.category}
const categories=computed(()=>[...new Set(props.catalog.map(group).filter(Boolean))])
const visible=computed(()=>props.catalog.filter(s=>(!category.value||group(s)===category.value)&&(!search.value||(s.name+' '+s.description).toLowerCase().includes(search.value.trim().toLowerCase()))))
function toggle(id:string){emit('update:modelValue',props.modelValue.includes(id)?props.modelValue.filter(s=>s!==id):[...props.modelValue,id])}
function selectVisible(){emit('update:modelValue',[...new Set([...props.modelValue,...visible.value.map(s=>s.service_id)])])}
function clearVisible(){const ids=new Set(visible.value.map(s=>s.service_id));emit('update:modelValue',props.modelValue.filter(id=>!ids.has(id)))}
</script>
<template><div class="service-picker"><div class="service-picker-tools"><label class="search-field"><Icon name="search"/><input v-model="search" type="search" aria-label="搜索检测服务" placeholder="搜索服务"></label><UiSelect v-model="category" aria-label="服务分类"><option value="">全部分类</option><option v-for="c in categories" :key="c" :value="c">{{c}}</option></UiSelect><button type="button" class="text-button" :disabled="!visible.length" @click="selectVisible">全选筛选项</button><button type="button" class="text-button" :disabled="!visible.length" @click="clearVisible">取消筛选项</button><span class="small muted">已选 {{modelValue.length}} 项</span></div><aside v-if="category==='IP 画像与信誉'" class="ip-reputation-intro"><p>按需选择所需规则。IPv4 / IPv6 独立；厂商分数不平均，不代表 ChatGPT / Netflix 实际可用。IPOK 每次先经所选节点读取出口，之后查询/复用该 IP 的画像，最多 2 个请求，共享原超时和 64KiB 响应上限。</p><p>外部查询入口：<a href="https://ipok.io/" target="_blank" rel="noopener noreferrer">IPOK ↗</a> · <a href="https://ippure.com/" target="_blank" rel="noopener noreferrer">IPPure ↗</a> · <a href="https://ip.net.coffee/ip/" target="_blank" rel="noopener noreferrer">NetCoffee ↗</a> · <a href="https://iplark.com/" target="_blank" rel="noopener noreferrer">IPLark ↗</a></p><p class="warn">浏览器当前网络可能不等于被测节点，请核对查询 IP。NetCoffee / IPLark 未接入自动查询。IPPure 旧规则观察 API 实际返回的地址族；未指定 IPv4/IPv6，不能替代固定地址族检测。</p></aside><div class="service-picker-list"><label v-for="s in visible" :key="s.service_id" :class="{checked:modelValue.includes(s.service_id)}"><input type="checkbox" :checked="modelValue.includes(s.service_id)" @change="toggle(s.service_id)"><span><strong>{{s.name}}</strong><small>{{s.description}}</small></span></label><p v-if="!visible.length" class="muted">没有匹配的服务。</p></div></div></template>
