<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {api,query,request} from '../api'
import {bytes,type Settings} from '../domain'
import {useWorkspace} from '../workspace'
import UiSelect from './UiSelect.vue'
import Icon from './Icon.vue'

interface Snapshot {account_key:string;airport_name:string;subscription_name:string;captured_at:string;status:string;upload:number|null;download:number|null;total?:number;source:string}
interface UsageInterval {account_key:string;name:string;from?:string;until:string;bytes:number|null;upload:number|null;download:number|null;status:string;estimated:boolean;message?:string}
interface UsageBucket {date:string;bytes:number|null;upload:number|null;download:number|null;intervals:number;estimated_intervals:number}
interface UsageReport {from:string;until:string;period:string;buckets:UsageBucket[];intervals:UsageInterval[];accounts:Snapshot[];observed_bytes:number|null;unallocated_bytes:number|null;unknown_intervals:number;daily_enabled:boolean;refresh?:{last_attempt:string;next_refresh:string;state:string;message:string}}
const w=useWorkspace(),period=ref('day'),account=ref(''),report=ref<UsageReport|null>(null),accounts=ref<Snapshot[]>([]),settings=ref<Settings|null>(null),error=ref(''),loading=ref(false),updating=ref(false),saving=ref(false),page=ref(1)
const todayParts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date())
const anchor=ref(['year','month','day'].map(k=>todayParts.find(p=>p.type===k)?.value).join('-'))
let generation=0,disposed=false,refreshTimer:ReturnType<typeof setTimeout>|undefined
const date=(value?:string)=>!value||value.startsWith('0001')?'—':new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})
const iso=(d:Date)=>d.toISOString().slice(0,10)
const range=computed(()=>{const d=new Date(anchor.value+'T00:00:00Z');if(!Number.isFinite(d.getTime()))return null;const y=d.getUTCFullYear(),m=d.getUTCMonth();let a:Date,b:Date;if(period.value==='month'){a=new Date(Date.UTC(y,m-11,1));b=new Date(Date.UTC(y,m+1,0))}else if(period.value==='week'){a=new Date(d);a.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);b=new Date(a);b.setUTCDate(b.getUTCDate()+6);a.setUTCDate(a.getUTCDate()-77)}else{a=new Date(Date.UTC(y,m,1));b=new Date(Date.UTC(y,m+1,0))}return {from:iso(a),until:iso(b)}})
const rows=computed(()=>report.value?.intervals.slice((page.value-1)*12,page.value*12)||[])
const pages=computed(()=>Math.max(1,Math.ceil((report.value?.intervals.length||0)/12)))
const maximum=computed(()=>Math.max(1,...(report.value?.buckets.map(b=>b.bytes||0)||[])))
const format=(n:number|null|undefined)=>n==null?'—':bytes(n)
const label=(s:string)=>({ok:'机场已报告',baseline:'首次基线',reset:'计数重置',missing:'未提供用量',local_file:'本地配置',refresh_failed:'更新失败',observed:'已观测',cross_period:'跨期区间'} as Record<string,string>)[s]||s
async function load(){clearTimeout(refreshTimer);const current=++generation;loading.value=true;error.value='';report.value=null;page.value=1;const r=range.value;if(!r){error.value='请选择有效日期';loading.value=false;return}try{const data=await request<UsageReport>('/api/subscription-usage?'+query({...r,period:period.value,account:account.value}),'GET',undefined,'GetSubscriptionUsage',[r.from,r.until,period.value,account.value]);if(disposed||current!==generation)return;report.value=data;if(data.refresh?.state==='running')refreshTimer=setTimeout(()=>{void load()},5000);if(!account.value&&data.accounts.length)accounts.value=data.accounts}catch(e){if(!disposed&&current===generation)error.value=e instanceof Error?e.message:String(e)}finally{if(!disposed&&current===generation)loading.value=false}}
async function update(){updating.value=true;error.value='';try{const result=await request<{message:string}>('/api/subscription-usage/refresh','POST',undefined,'UpdateSubscriptionUsage');if(disposed)return;await w.refreshNodes();await load();w.notify(result.message)}catch(e){if(!disposed)error.value=e instanceof Error?e.message:String(e)}finally{if(!disposed)updating.value=false}}
async function saveDaily(event:Event){if(!settings.value)return;const enabled=(event.target as HTMLInputElement).checked,old=settings.value.subscription_daily_update_enabled;saving.value=true;error.value='';try{const next={...settings.value,subscription_daily_update_enabled:enabled};await api.saveSettings(next);settings.value=next;if(report.value)report.value.daily_enabled=enabled;w.notify(enabled?'已开启每日订阅更新':'已关闭每日订阅更新')}catch(e){settings.value.subscription_daily_update_enabled=old;(event.target as HTMLInputElement).checked=old??true;error.value=e instanceof Error?e.message:String(e)}finally{saving.value=false}}
function move(direction:number){const d=new Date(anchor.value+'T00:00:00Z');if(!Number.isFinite(d.getTime()))return;if(period.value==='week')d.setUTCDate(d.getUTCDate()+direction*7);else{d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+direction)}anchor.value=iso(d)}
watch([period,anchor,account],()=>{void load()})
onMounted(()=>{void load();void api.settings().then(s=>settings.value=s).catch(e=>error.value=e instanceof Error?e.message:String(e))})
onBeforeUnmount(()=>{disposed=true;generation++;clearTimeout(refreshTimer)})
</script>

<template><section class="subscription-usage" aria-label="订阅用量监测">
  <div class="usage-schedule"><div><h2>每日订阅更新与用量记录</h2><p>先更新订阅，再保存机场返回的累计上传、下载量。服务运行时每天 00:05（上海时间）更新，停机错过后启动补采一轮。</p><label class="check-field"><input type="checkbox" :checked="settings?.subscription_daily_update_enabled??report?.daily_enabled" :disabled="!settings||saving" @change="saveDaily">每日自动更新订阅</label><small v-if="report?.refresh">上次尝试 {{date(report.refresh.last_attempt)}} · {{report.daily_enabled?'下次 '+date(report.refresh.next_refresh):'自动更新已关闭'}}<br>{{report.refresh.message}}</small></div><button class="button primary" :disabled="updating||saving" @click="update"><Icon name="refresh"/>{{updating?'更新并记录中…':'立即更新并记录'}}</button></div>
  <div class="page-toolbar usage-toolbar"><div class="segmented" role="group" aria-label="用量汇总周期"><button v-for="p in [{id:'day',label:'日用量'},{id:'week',label:'周汇总'},{id:'month',label:'月汇总'}]" :key="p.id" class="button" :class="{active:period===p.id}" :aria-pressed="period===p.id" @click="period=p.id">{{p.label}}</button></div><div class="button-group"><button class="button icon-button" aria-label="查看前一范围" @click="move(-1)"><Icon name="chevron" class="usage-previous"/></button><label class="usage-date">参照日期<input v-model="anchor" type="date" aria-label="用量参照日期"></label><button class="button icon-button" aria-label="查看后一范围" @click="move(1)"><Icon name="chevron"/></button><UiSelect v-model="account" aria-label="用量订阅账户"><option value="">全部订阅账户</option><option v-for="a in accounts" :key="a.account_key" :value="a.account_key">{{a.airport_name}} · {{a.subscription_name}}</option></UiSelect></div></div>
  <p v-if="error" class="inline-error" role="alert">{{error}} <button class="text-button" @click="load">重新读取</button></p>
  <p v-if="loading" class="muted" role="status">正在读取用量历史…</p>
  <template v-if="report"><p class="muted small">{{report.from}} — {{report.until}} · 上海时间 · 相同订阅地址合并统计，不同地址可能属于同一账户，请按账户查看。</p><div class="usage-summary"><div><small>本范围已归属增量</small><strong>{{report.observed_bytes==null?'待积累':bytes(report.observed_bytes)}}</strong><span>已观测区间合计，未记录部分未知</span></div><div><small>跨期区间增量</small><strong>{{format(report.unallocated_bytes)}}</strong><span>未按天数摊分，详见观测记录</span></div><div><small>未知或基线记录</small><strong>{{report.unknown_intervals}}</strong><span>首次、重置、失败不当作零用量</span></div></div>
  <p class="usage-explanation">用量来自机场账户计数，不是本工作台探测流量。日用量为更新区间增量；近午夜更新归前一日并标注估算。漏采跨日、计数重置和缺少用量字段均保留记录，周、月汇总也只累计能归属的观测区间。</p>
  <div class="usage-chart" role="img" :aria-label="`${period==='day'?'日':period==='week'?'周':'月'}用量观测柱状图；灰色表示无可归属数据`"><div v-for="b in [...report.buckets].reverse()" :key="b.date" class="usage-bar" :class="{unknown:b.bytes==null}" :title="`${b.date} · ${b.bytes==null?'暂无可归属数据':bytes(b.bytes)}${b.estimated_intervals?' · 含区间估算':''}`"><i :style="{height:b.bytes==null?'3px':`${Math.max(3,b.bytes/maximum*92)}px`}"/><small>{{period==='month'?b.date.slice(5):b.date.slice(5)}}</small></div></div>
  <div class="table-scroll"><table class="usage-buckets"><thead><tr><th>{{period==='day'?'日期':period==='week'?'周一开始':'月份'}}</th><th>已观测增量</th><th>上传</th><th>下载</th><th>记录范围</th></tr></thead><tbody><tr v-for="b in report.buckets" :key="b.date"><td>{{b.date}}</td><td>{{format(b.bytes)}}</td><td>{{format(b.upload)}}</td><td>{{format(b.download)}}</td><td>{{b.bytes==null?'暂无可归属数据':`${b.intervals} 个区间`}}<span v-if="b.estimated_intervals" class="badge">含 {{b.estimated_intervals}} 个估算区间</span></td></tr></tbody></table></div>
  <h3>账户最近观测</h3><div class="usage-accounts"><article v-for="a in report.accounts" :key="a.account_key"><strong>{{a.airport_name}} · {{a.subscription_name}}</strong><span>{{label(a.status)}} · {{date(a.captured_at)}}</span><span v-if="a.upload!=null&&a.download!=null">累计 {{bytes(a.upload+a.download)}}<template v-if="a.total"> / {{bytes(a.total)}}</template></span><span v-else>用量未知</span><small v-if="a.source==='cached_baseline'">来自已有缓存的旧快照，并非本次采集</small></article></div>
  <h3>观测记录</h3><div class="table-scroll"><table class="usage-intervals"><thead><tr><th>订阅账户</th><th>观测区间</th><th>增量</th><th>状态与说明</th></tr></thead><tbody><tr v-for="(i,index) in rows" :key="i.account_key+i.until+index"><td>{{i.name}}</td><td>{{i.from?date(i.from):'首次记录'}} → {{date(i.until)}}</td><td>{{format(i.bytes)}}</td><td>{{label(i.status)}}<span v-if="i.estimated"> · 区间估算</span><small v-if="i.message">{{i.message}}</small></td></tr></tbody></table></div><div v-if="!report.intervals.length" class="empty-state compact"><p>这个范围还没有用量记录。首次更新建立基线，后续才能计算增量。</p></div><div class="page-toolbar"><span class="small muted">{{report.intervals.length}} 条观测记录</span><div class="button-group"><button class="button" :disabled="page<=1" @click="page--">上一页</button><span>{{page}} / {{pages}}</span><button class="button" :disabled="page>=pages" @click="page++">下一页</button></div></div>
  </template>
</section></template>
