<script setup lang="ts">
import {nodeDisplayName} from '../nodePresentation'
import UiSelect from './UiSelect.vue'
import {computed,ref} from 'vue'
import {useWorkspace} from '../workspace'
import {bytes,projectNames,targets,type Project} from '../domain'
import Modal from './Modal.vue'
import ServicePicker from './ServicePicker.vue'
const w=useWorkspace(),submitting=ref(false),validation=ref('')
const downloadVolume=computed(()=>w.plan.value?.projects.includes('download')?w.plan.value.nodes.length*w.plan.value.downloadMiB*1048576*w.plan.value.repeats:0)
const groups=computed(()=>[...new Map(w.plan.value?.nodes.map(n=>[n.profile_id,{name:n.profile_name,count:w.plan.value!.nodes.filter(x=>x.profile_id===n.profile_id).length}])||[]).values()])
async function submit(){validation.value='';if(!w.plan.value?.projects.length){validation.value='至少选择一个检测项目';return}if(w.plan.value.projects.includes('service')&&!w.plan.value.serviceIds.length){validation.value='至少选择一个服务';return}submitting.value=true;try{await w.runPlan()}catch(e){validation.value=e instanceof Error?e.message:String(e)}finally{submitting.value=false}}
</script>
<template><Modal v-if="w.plan.value" title="配置这次检测" wide @close="w.plan.value=null"><div class="plan-scope"><strong>{{w.plan.value.nodes.length}} 个节点</strong><span v-for="g in groups" :key="g.name">{{g.name}} · {{g.count}}</span></div><div class="plan-projects"><label v-for="p in (['latency','download','service'] as Exclude<Project,'combined'>[])" :key="p" :class="{checked:w.plan.value.projects.includes(p)}"><input v-model="w.plan.value.projects" type="checkbox" :value="p">{{projectNames[p]}}</label></div><div v-if="w.plan.value.projects.includes('latency')" class="plan-section"><h3>延迟检测</h3><div class="form-grid"><label>检测站点<UiSelect v-model="w.plan.value.target"><option value="all">六站综合检测</option><option v-for="target in targets" :key="target.id" :value="target.id">{{target.name}}</option></UiSelect></label><label>每站采样次数<UiSelect v-model.number="w.plan.value.samples"><option v-for="n in [1,3,6,10,20]" :key="n" :value="n">{{n}} 次</option></UiSelect></label><label>请求超时<UiSelect v-model.number="w.plan.value.timeout"><option v-for="n in [3,5,10,20,30]" :key="n" :value="n">{{n}} 秒</option></UiSelect></label><label>节点并发<UiSelect v-model.number="w.plan.value.concurrency"><option v-for="n in [1,4,8,16]" :key="n" :value="n">{{n}} 个节点</option></UiSelect></label></div></div><div v-if="w.plan.value.projects.includes('download')" class="plan-section"><h3>下载测速</h3><div class="form-grid"><label>每节点最多读取<UiSelect v-model.number="w.plan.value.downloadMiB"><option v-for="n in [5,10,20,50,100]" :key="n" :value="n">{{n}} MiB</option></UiSelect></label><label>每节点最多持续<UiSelect v-model.number="w.plan.value.downloadSeconds"><option v-for="n in [5,10,20,30]" :key="n" :value="n">{{n}} 秒</option></UiSelect></label></div><p class="muted small">逐个下载，避免抢占带宽。本次最多读取 {{bytes(downloadVolume)}}；实际扣费还受机场倍率和协议开销影响。</p></div><div v-if="w.plan.value.projects.includes('service')" class="plan-section"><h3>服务可用性</h3><ServicePicker v-model="w.plan.value.serviceIds" :catalog="w.catalog.value"/><p v-if="w.plan.value.serviceIds.includes('antigravity')" class="inline-warning">Antigravity 会用已绑定账号发起真实模型请求，可能消耗额度。</p></div><label class="inline-field">重复检测<UiSelect v-model.number="w.plan.value.repeats"><option v-for="n in [1,2,3,5]" :key="n" :value="n">{{n}} 轮</option></UiSelect></label><details class="selection-details"><summary>核对所选 {{w.plan.value.nodes.length}} 个节点</summary><div v-for="n in w.plan.value.nodes" :key="n.profile_id+n.node_key" class="compact-row"><span>{{nodeDisplayName(n)}}</span><small>{{n.profile_name}}</small></div></details><p v-if="validation" class="inline-error" role="alert">{{validation}}</p><template #footer><button class="button" @click="w.plan.value=null">返回调整</button><button class="button primary" :disabled="submitting||w.busy.value" @click="submit">开始检测 {{w.plan.value.nodes.length}} 个节点</button></template></Modal></template>
