import type {Airport,Attempt,HistoryPage,LatencyBatch,LatencyTest,MonitorCreate,MonitorJob,MonitorSample,NodeOption,NodeScope,ServiceRule,Settings,Setup,TokenStatus} from './domain'
import {scope} from './domain'
declare global {interface Window {go?:{desktop?:{App?:Record<string,(...args:any[])=>Promise<any>>}};runtime?:{EventsOn:(name:string,callback:(payload:any)=>void)=>()=>void}}}
export const desktop=()=>!!window.go?.desktop?.App
let token=window.localStorage.getItem('cst_auth_token')||''
export function query(params:object={}){const out=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v!==undefined&&v!==null&&v!=='')out.set(k,String(v));return out.toString()}
export async function request<T>(path:string,method='GET',body?:unknown,desktopMethod?:string,args:unknown[]=[]):Promise<T>{
  if(desktop()&&desktopMethod){const fn=window.go!.desktop!.App![desktopMethod];if(!fn)throw new Error('当前桌面版本需要更新才能使用此功能');return fn(...args)}
  const headers:Record<string,string>={};if(token)headers.Authorization=`Bearer ${token}`;if(body!==undefined)headers['Content-Type']='application/json'
  const res=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});if(!res.ok){if(res.status===401)window.dispatchEvent(new Event('speedtest:auth-required'));const raw=await res.text();let message=raw;try{message=JSON.parse(raw).error||raw}catch{}throw Object.assign(new Error(message||`请求失败 (${res.status})`),{status:res.status})}const raw=await res.text();return raw?JSON.parse(raw):undefined
}
const attemptPath=(k:'download'|'service')=>`/api/workbench/${k==='service'?'public-service':'download'}-tests`
function attemptScope(kind:'download'|'service',n:NodeScope&{service_id?:string},serviceId=n.service_id){if(kind==='service'&&!serviceId)throw new Error('服务检测详情缺少服务标识，请刷新后重试');return {...scope(n),...(kind==='service'?{service_id:serviceId}:{})}}
export const api={
  auth:()=>desktop()?Promise.resolve({auth_required:false,authenticated:true}):request<{auth_required:boolean;authenticated:boolean}>('/api/auth/status'),
  async login(password:string){const data=await request<{token:string}>('/api/auth/login','POST',{password});token=data.token;window.localStorage.setItem('cst_auth_token',token)},
  setup:()=>request<Setup>('/api/profile/setup','GET',undefined,'GetProfileSetup'),airports:()=>request<Airport[]>('/api/airports','GET',undefined,'ListAirports'),nodes:()=>request<NodeOption[]>('/api/monitor/nodes','GET',undefined,'ListMonitorNodeOptions'),catalog:()=>request<ServiceRule[]>('/api/workbench/public-service-catalog','GET',undefined,'ListWorkbenchPublicServiceCatalog'),jobs:()=>request<MonitorJob[]>('/api/monitor/jobs','GET',undefined,'ListMonitorJobs'),
  createJob:(body:MonitorCreate)=>request<MonitorJob>('/api/monitor/jobs','POST',body,'CreateMonitorJob',[body]),
  jobAction:(id:string,action:string,body?:unknown)=>request(`/api/monitor/jobs/${encodeURIComponent(id)}/${action}`,'POST',body,({start:'StartMonitorJob',pause:'PauseMonitorJob',resume:'ResumeMonitorJob',stop:'StopMonitorJob',trigger:'TriggerMonitorJob','resume-on-launch':'SetMonitorJobResumeOnLaunch','sampling-tier':'UpdateMonitorJobSamplingTier'} as Record<string,string>)[action],[id,...(body?Object.values(body):[])]),
  deleteJob:(id:string)=>request(`/api/monitor/jobs/${encodeURIComponent(id)}`,'DELETE',undefined,'DeleteMonitorJob',[id]),
  batches:()=>request<LatencyBatch[]>('/api/workbench/latency-batches?limit=30','GET',undefined,'ListWorkbenchLatencyBatches',[30]),startLatency:(body:unknown)=>request<LatencyBatch>('/api/workbench/latency-batches','POST',body,'StartWorkbenchLatencyBatch',[body]),batch:(id:string)=>request<LatencyBatch>(`/api/workbench/latency-batches/${encodeURIComponent(id)}`,'GET',undefined,'GetWorkbenchLatencyBatch',[id]),cancelBatch:(id:string)=>request<LatencyBatch>(`/api/workbench/latency-batches/${encodeURIComponent(id)}/cancel`,'POST',undefined,'CancelWorkbenchLatencyBatch',[id]),retryBatch:(id:string,item:string)=>request<LatencyBatch>(`/api/workbench/latency-batches/${encodeURIComponent(id)}/items/${encodeURIComponent(item)}/retry-save`,'POST',undefined,'RetryWorkbenchLatencyBatchItem',[id,item]),
  async latencySummaries(nodes:NodeScope[],since?:string,until?:string,limit=12){if(!nodes.length)return [];if(!desktop())return request<HistoryPage<LatencyTest>[]>('/api/workbench/latency-tests/query','POST',{nodes:nodes.map(scope),since,until,limit});return mapLimited(nodes,4,n=>api.latencyHistory(n,{since,until,limit}))},
  latencyHistory:(n:NodeScope,extra:Record<string,unknown>={})=>{const q={...scope(n),...extra};return request<HistoryPage<LatencyTest>>(`/api/workbench/latency-tests?${query(q)}`,'GET',undefined,'ListWorkbenchLatencyTests',[q])},
  startAttempt:(kind:'download'|'service',body:unknown)=>request<Attempt>(attemptPath(kind),'POST',body,kind==='service'?'StartWorkbenchPublicServiceTest':'StartWorkbenchDownloadTest',[body]),
  attempt:(kind:'download'|'service',id:string,n:NodeScope&{service_id?:string},serviceId?:string)=>{const q=attemptScope(kind,n,serviceId);return request<Attempt>(`${attemptPath(kind)}/${encodeURIComponent(id)}?${query(q)}`,'GET',undefined,kind==='service'?'GetWorkbenchPublicServiceAttempt':'GetWorkbenchDownloadAttempt',[id,q])},
  attemptAction:(kind:'download'|'service',id:string,n:NodeScope&{service_id?:string},action:'cancel'|'retry-save',serviceId?:string)=>{const q=attemptScope(kind,n,serviceId);return request<Attempt>(`${attemptPath(kind)}/${encodeURIComponent(id)}/${action}?${query(q)}`,'POST',undefined,(action==='cancel'?'Cancel':'RetrySave')+(kind==='service'?'WorkbenchPublicServiceTest':'WorkbenchDownloadTest'),[id,q])},
  attemptHistory:(kind:'download'|'service',n:NodeScope,extra:Record<string,unknown>={})=>{const q={...scope(n),...extra};return request<HistoryPage<Attempt>>(`${attemptPath(kind)}?${query(q)}`,'GET',undefined,kind==='service'?'ListWorkbenchPublicServiceTests':'ListWorkbenchDownloadTests',[q])},
  monitorSamples:(q:Record<string,unknown>)=>request<{items:MonitorSample[];has_more:boolean;next_cursor:string}>(`/api/monitor/samples/cursor?${query(q)}`,'GET',undefined,'QueryMonitorSamplesCursor',[q]),monitorStats:(q:Record<string,unknown>)=>request<Record<string,any>>(`/api/monitor/stats?${query(q)}`,'GET',undefined,'GetMonitorStats',[q]),monitorFacets:(since:string,until:string)=>request<{nodes:{node_key:string;node_identity_key:string;profile_id:string;display_name:string}[];profiles:string[];targets:string[]}>(`/api/monitor/facets?${query({since,until})}`,'GET',undefined,'GetMonitorSampleFacets',[since,until]),
  settings:()=>request<Settings>('/api/settings','GET',undefined,'GetSettings'),saveSettings:(s:Settings)=>request('/api/settings','POST',s,'SaveSettings',[s]),token:()=>request<TokenStatus>('/api/antigravity/status','GET',undefined,'GetTokenStatus'),setToken:(value:string)=>request('/api/antigravity/token','POST',{token:value},'SetToken',[value]),oauth:()=>request('/api/antigravity/login','POST',undefined,'StartOAuthLogin'),
  initialize:()=>request('/api/profile/setup/empty','POST',undefined,'InitializeEmptyProfileStore'),inspect:(path:string)=>request<Record<string,any>>('/api/profile/source/inspect','POST',{path},'InspectProfileSource',[path]),importSource:(path:string)=>request('/api/profile/import','POST',{path},'ImportProfileSource',[path]),migrate:()=>request('/api/data/migration','POST',undefined,'MigrateLegacyData'),discardImport:()=>request('/api/profile/import/discard','POST',undefined,'DiscardProfileImport'),storage:()=>request<Record<string,any>>('/api/monitor/storage','GET',undefined,'GetMonitorStorageUsage'),budget:()=>request<Record<string,any>>('/api/monitor/budget','GET',undefined,'GetMonitorBudgetStatus'),
  exportClash:(nodes:NodeScope[])=>request<{yaml_content:string;node_count:number}>('/api/workbench/export-clash','POST',{node_keys:nodes.map(n=>n.node_key)},'ExportNodesClashConfig',[{node_keys:nodes.map(n=>n.node_key)}]),revisions:(n:NodeScope)=>request<{config_revision_key:string;node_key:string;display_name:string;last_observed_at:string}[]>(`/api/history/node-revisions?${query({profile_id:n.profile_id,node_identity_key:n.node_identity_key})}`,'GET',undefined,'ListNodeHistoryRevisions',[n.profile_id,n.node_identity_key]),
}
export async function mapLimited<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>):Promise<R[]>{const result=new Array<R>(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const i=cursor++;result[i]=await fn(items[i],i)}}));return result}
export function events(onEvent:(type:string,payload:any)=>void,onConnection:(connected:boolean)=>void){if(desktop()&&window.runtime){const names=['workbench_latency_batch_updated','workbench_latency_test_completed','workbench_latency_test_persistence_updated','workbench_download_progress','workbench_download_attempt_updated','workbench_public_service_attempt_updated','antigravity_token_updated','antigravity_login_failed'];const offs=names.map(n=>window.runtime!.EventsOn(n,p=>onEvent(n,p)));onConnection(true);return ()=>offs.forEach(fn=>fn())}const stream=new EventSource(`/api/events${token?'?'+query({token}):''}`);stream.onopen=()=>onConnection(true);stream.onerror=()=>onConnection(false);stream.onmessage=e=>{try{const data=JSON.parse(e.data);onEvent(data.type,data.payload)}catch{}};return ()=>stream.close()}
export async function saveFile(contents:string,name:string,type='text/plain'):Promise<boolean>{if(desktop())return request<boolean>('','POST',undefined,'SaveTextFile',[contents,name]);const url=URL.createObjectURL(new Blob([contents],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true}
export async function backup():Promise<boolean>{if(desktop())return request<boolean>('','POST',undefined,'ExportDataBackup');const res=await fetch('/api/data/export',{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!res.ok)throw new Error(await res.text());const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=`speedtest-data-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true}
export function selectProfileSourceDirectory(){return request<string>('','POST',undefined,'SelectProfileSourceDirectory')}
