export type Page = 'home'|'airports'|'monitor'|'history'|'settings'|'data'
export type Project = 'latency'|'download'|'service'|'combined'
export interface NodeScope { profile_id:string;node_key:string;node_identity_key:string;config_revision_key:string }
export interface NodeOption extends NodeScope { profile_name:string;display_name:string;type:string;country_code:string;country_flag:string }
export interface Subscription { id:string;airport_id:string;name:string;url_display:string;url_configured:boolean;note?:string;updated_at?:string;node_count:number;has_cache:boolean;status?:string;usage?:{upload:number;download:number;total?:number;expire?:number} }
export interface Airport { id:string;name:string;subscriptions?:Subscription[];website_url?:string;backup_url?:string;note?:string;url_display:string;node_count:number;has_cache:boolean;updated_at?:string;maintenance?:{refresh_hours:number;next_refresh?:string;last_result?:string;links:{label:string;url:string;monthly_day:number;done_month?:string}[]} }
export interface LatencySample {seq:number;target?:string;timestamp:string;latency_ms:number;success:boolean;error?:string}
export interface LatencyTest extends NodeScope {attempt_id:string;display_name:string;node_type:string;target?:string;requested_at:string;finished_at:string;status:string;latency_ms:number;total_samples:number;success_samples:number;failure_samples:number;samples:LatencySample[];persistence_state:string;persistence_error?:string;error_message?:string}
export interface BatchItem extends NodeScope {item_id:string;batch_id:string;display_name:string;execution_state:string;persistence_state:string;persistence_error?:string;error_message?:string;result?:LatencyTest}
export interface LatencyBatch {batch_id:string;request_id:string;target_id?:string;state:string;requested_at:string;sample_count?:number;item_count:number;items?:BatchItem[]}
export interface ServiceRule {service_id:string;name:string;category:string;description:string;region?:string;result_kind:string;success_criterion:string;timeout_seconds:number;batch_default?:boolean}
export interface Attempt extends NodeScope {attempt_id:string;request_id:string;display_name:string;node_type?:string;service_id?:string;requested_at:string;finished_at?:string;execution_state:string;persistence_state:string;persistence_error?:string;rule:{service_id?:string;name?:string;target_url:string;success_criterion?:string;maximum_bytes?:number;maximum_duration_ns?:number};result?:{outcome:string;bytes_read:number;duration_ns?:number;duration_ms?:number;finished_at:string;error_message?:string;summary?:string;http_status?:number;details?:Record<string,unknown>;samples?:{elapsed_ns:number;speed_mbps?:number;cumulative_bytes:number}[]}}
export interface HistoryPage<T> {tests?:T[];attempts?:T[];has_more:boolean;complete:boolean}
export interface MonitorJob {id:string;name:string;profile_id:string;profile_name:string;nodes:NodeOption[];node_keys:string[];probe_set:string;sampling_tier:string;interval_seconds:number;timeout_seconds:number;state:string;resume_on_launch:boolean;blocked_reason?:string;recovery_reason?:string;persistence_error?:string;storage_reason?:string;budget_reason?:string;updated_at:string}
export interface MonitorCreate {name:string;profile_id:string;node_keys:string[];node_contexts:Pick<NodeScope,'node_key'|'node_identity_key'|'config_revision_key'>[];probe_set:string;sampling_tier:string;interval_seconds:number;timeout_seconds:number}
export interface MonitorSample extends NodeScope {sample_id:string;run_id?:string;display_name_snapshot:string;timestamp:string;target:string;probe_type:string;success:boolean;latency:number;ttfb:number;error_class?:string;error_detail?:string;sampling_tier:string}
export interface Setup {state:string;initialized:boolean;data_root:string;profile_dir:string;history_dir:string;settings_file:string;error?:string;sources?:{path:string;label:string;available:boolean;profile_count:number;cache_count:number;error?:string}[];migration:{state:string;error?:string;source_history_dir?:string;target_history_dir:string}}
export interface Settings {subscription_daily_update_enabled?:boolean;preferred_browser:string;monitor_retention_policy:string;monitor_retention_custom_days:number;monitor_storage_warning_bytes?:number;monitor_storage_hard_bytes?:number;monitor_budget_max_concurrent?:number;monitor_budget_response_bytes?:number;favorite_services?:string[];selected_profile_id?:string}
export interface TokenStatus {has_token:boolean;source:string;preview:string}
export interface Plan {nodes:NodeOption[];projects:Exclude<Project,'combined'>[];target:string;samples:number;timeout:number;concurrency:number;downloadMiB:number;downloadSeconds:number;serviceIds:string[];repeats:number}
export interface QueueItem {id:string;node:NodeOption;project:Exclude<Project,'combined'>;serviceId?:string;state:string;error?:string;batchId?:string;itemId?:string;attempt?:Attempt}
export const projectNames:Record<Project,string>={latency:'延迟检测',download:'下载测速',service:'服务可用性',combined:'综合'}
export const targets=[{id:'cloudflare',name:'Cloudflare',match:'speed.cloudflare.com'},{id:'google',name:'Google',match:'gstatic.com'},{id:'github',name:'GitHub',match:'api.github.com'},{id:'apple',name:'Apple',match:'captive.apple.com'},{id:'microsoft',name:'Microsoft',match:'msftconnecttest.com'},{id:'firefox',name:'Firefox',match:'detectportal.firefox.com'}]
export function key(n:NodeScope){return `${n.profile_id}\u0000${n.node_identity_key}\u0000${n.config_revision_key}`}
export function scope(n:NodeScope):NodeScope{return {profile_id:n.profile_id,node_key:n.node_key,node_identity_key:n.node_identity_key,config_revision_key:n.config_revision_key}}
export function isNotice(n:NodeOption){
  const name=n.display_name.trim().replace(/^[\p{P}\p{S}\s]+/u,'')
  if(/^(?:公告|机场公告|通知|重要提示|订阅地址(?:失效|过期)|使用说明|官网地址|官方网址|官方地址|防失联(?:页|地址|网址)?|电报群|交流群|官方(?:群|频道)|telegram\s*(?:group|channel)|tg\s*(?:群|频道))\s*[:：\s]?/i.test(name))return true
  if(/^\[[^\]\r\n]{1,30}\][✨\s]*(?:永久|官网|网址|备用)[:：]{2,}[^|\s]+\.[a-z]{2,}(?:$|\s)/i.test(n.display_name.trim()))return true
  if(/(?:电报群|交流群|防失联|官网|官方地址|备用网址|使用文档|客户端).*(?:https?:\/\/|t\.me\/)/i.test(name)||/^https?:\/\/(?:t\.me|telegram\.me|github\.com)\//i.test(name))return true
  // Account metadata is a notice even when a unit such as GB resembles a region code.
  if(/^(?:剩余流量|套餐到期|到期时间|订阅到期|套餐有效期|有效期[至:：]|流量重置(?:时间|日期|[：:])|订阅更新(?:时间|日期|[：:]))/.test(name))return true
  if(/^(?:如果只(?:显示|看到)(?:此|一个)?节点|是客户端太旧|更新(?:一下|你的)?客户端|请到(?:官网|网站).*(?:教程|使用说明)|请重新(?:复制)?导入)/.test(name))return true
  // Keep region-bearing route names intact when they include instructions.
  if(/^[A-Z]{2}$/i.test(n.country_code||'')&&!['XX','ZZ'].includes(n.country_code.toUpperCase()))return false
  return /每次使用前.*更新订阅|(?:请|使用前|务必).*(?:重新导入|更新订阅|阅读.*(?:说明|文档)|下载.*客户端)|(?:用不了|无法使用).*(?:客户端|重新导入)|(?:不够|不会使用).*(?:官网|使用文档|客户端)/.test(name)
}
export function monitorGroups(nodes:NodeOption[],name:string,interval:number,timeout:number,probe:string,tier:string):MonitorCreate[]{const groups=new Map<string,NodeOption[]>();for(const n of nodes){if(!n.node_identity_key||!n.config_revision_key)throw new Error('节点配置已变化，请刷新后重新选择');const list=groups.get(n.profile_id)||[];list.push(n);groups.set(n.profile_id,list)}return Array.from(groups,([id,list])=>({name:groups.size>1?`${name} · ${list[0].profile_name}`:name,profile_id:id,node_keys:list.map(n=>n.node_key),node_contexts:list.map(n=>({node_key:n.node_key,node_identity_key:n.node_identity_key,config_revision_key:n.config_revision_key})),probe_set:probe,sampling_tier:tier,interval_seconds:interval,timeout_seconds:timeout}))}
export function median(values:number[]){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),m=Math.floor(sorted.length/2);return sorted.length%2?sorted[m]:(sorted[m-1]+sorted[m])/2}
export function sampleFor(test:LatencyTest,target:string){const t=targets.find(t=>t.id===target);return (test.samples||[]).filter(s=>t?s.target?.includes(t.match)||(!s.target&&target==='cloudflare'):true)}
export function latencyFor(test:LatencyTest|undefined,target='cloudflare'){if(!test)return null;return median(sampleFor(test,target).filter(s=>s.success).map(s=>s.latency_ms))}
export function downloadSpeed(a:Attempt|undefined){const r=a?.result;return r?.duration_ns&&r.bytes_read>0?r.bytes_read/1048576/(r.duration_ns/1e9):null}
export function downloadTone(a:Attempt){const r=a.result;if(!r)return 'empty';return r.bytes_read>0&&['completed','byte_limit','time_limit'].includes(r.outcome)?'good':'bad'}
export function outcomeLabel(v?:string){return ({matched:'通过',reachable:'可访问',unlocked:'已解锁',profiled:'已获取',challenge:'验证挑战',rate_limited:'限流',originals_only:'仅自制内容',region_limited:'部分地区受限',region_blocked:'地区受限',credentials_required:'需要凭据',auth_failed:'凭据无效',permission_denied:'权限不足',timed_out:'超时',failed:'失败',completed:'完成',byte_limit:'达到流量上限',time_limit:'达到时间上限',connection_failed:'连接失败',transfer_interrupted:'传输中断',transport_error:'连接或读取失败',http_rejected:'HTTP 拒绝',service_rejected:'服务拒绝',criteria_mismatch:'未符合判断条件',redirect:'返回重定向',unknown:'未确认',user_cancelled:'已取消',cancelled:'已取消',interrupted:'已中断'} as Record<string,string>)[v||'']||v||'尚未检测'}
export function outcomeTone(v?:string){return ['matched','reachable','unlocked','profiled','completed'].includes(v||'')?'good':['challenge','rate_limited','originals_only','region_limited','credentials_required','auth_failed','permission_denied','unknown'].includes(v||'')?'warn':'bad'}
export function stateLabel(v?:string){return ({queued:'排队中',running:'检测中',saving:'保存中',saved:'已保存',completed:'完成',completed_with_issues:'完成 · 部分检测异常',completed_with_save_failures:'完成 · 部分保存失败',failed:'失败',cancelled:'已取消',cancelled_with_issues:'已取消 · 部分检测异常',cancelled_with_save_failures:'已取消 · 部分保存失败',cancelling:'正在取消',interrupted:'已中断',interrupted_with_issues:'已中断 · 部分检测异常',interrupted_with_save_failures:'已中断 · 部分保存失败',not_executed:'未执行',skipped_config:'配置已变化',pending:'待保存',not_started:'待保存',paused:'已暂停',stopped:'未运行',blocked:'受限',not_applicable:'无需保存'} as Record<string,string>)[v||'']||v||'—'}
export function bytes(n=0){return n>=1073741824?`${(n/1073741824).toFixed(2)} GiB`:n>=1048576?`${(n/1048576).toFixed(1)} MiB`:n>=1024?`${(n/1024).toFixed(1)} KiB`:`${n} B`}
export function date(v?:string){if(!v||v.startsWith('0001'))return '—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
